// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVZXmdMA0rQSrh2YWQdF2jUD2eghpOEzY',
    appId: '1:435646997891:web:1aa37b8c1e79688cf842b6',
    messagingSenderId: '435646997891',
    projectId: 'devriti-b1f3f',
    storageBucket: 'devriti-b1f3f.firebasestorage.app',
    iosBundleId: 'com.devriti.selfcare',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVZXmdMA0rQSrh2YWQdF2jUD2eghpOEzY',
    appId: '1:435646997891:android:1aa37b8c1e79688cf842b6',
    messagingSenderId: '435646997891',
    projectId: 'devriti-b1f3f',
    storageBucket: 'devriti-b1f3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZXmdMA0rQSrh2YWQdF2jUD2eghpOEzY',
    appId: '1:435646997891:ios:1aa37b8c1e79688cf842b6',
    messagingSenderId: '435646997891',
    projectId: 'devriti-b1f3f',
    storageBucket: 'devriti-b1f3f.firebasestorage.app',
    iosBundleId: 'com.devriti.selfcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVZXmdMA0rQSrh2YWQdF2jUD2eghpOEzY',
    appId: '1:435646997891:web:1aa37b8c1e79688cf842b6',
    messagingSenderId: '435646997891',
    projectId: 'devriti-b1f3f',
    storageBucket: 'devriti-b1f3f.firebasestorage.app',
    authDomain: 'devriti-b1f3f.firebaseapp.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVZXmdMA0rQSrh2YWQdF2jUD2eghpOEzY',
    appId: '1:435646997891:ios:1aa37b8c1e79688cf842b6',
    messagingSenderId: '435646997891',
    projectId: 'devriti-b1f3f',
    storageBucket: 'devriti-b1f3f.firebasestorage.app',
    iosBundleId: 'com.devriti.selfcare',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCVZXmdMA0rQSrh2YWQdF2jUD2eghpOEzY',
    appId: '1:435646997891:web:1aa37b8c1e79688cf842b6',
    messagingSenderId: '435646997891',
    projectId: 'devriti-b1f3f',
    storageBucket: 'devriti-b1f3f.firebasestorage.app',
    authDomain: 'devriti-b1f3f.firebaseapp.com',
  );
}
